# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Install CUE
        run: go install cuelang.org/go/cmd/cue@latest

      - name: Generate
        run: go generate -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test Main
        run: go test -v ./...

      - name: Test CUE
        run: go test -v ./languages/cue/...
